name: Letterboxd Notifier

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Checker
        env:
          FEED_URL: ${{ secrets.FEED_URL }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: |
          python main.py

      - name: Commit State
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add state.json

          git diff --cached --quiet || git commit -m "Update state"

          git push